#!/usr/bin/env python3
"""Regenerate config.example.toml from conscio.config.default_config_text.

Run from the repo root:  uv run python scripts/regen-config-example.py
tests/test_config_example.py fails CI when the committed file drifts.
"""

from __future__ import annotations

from pathlib import Path

from conscio.config import default_config_text

HEADER = (
    "# Example Conscio configuration. Copy to ~/.conscio/config.toml and replace\n"
    "# the placeholder secrets. Generated by scripts/regen-config-example.py —\n"
    "# edit conscio/config.py (default_config_text) instead of this file.\n\n"
)


def render() -> str:
    return HEADER + default_config_text(
        profile="research",
        home="/home/conscio/.conscio",
        api_key="replace-me",
        web_password="replace-me-too",
        working_directory="/opt/conscio/work",
    )


if __name__ == "__main__":
    out = Path(__file__).resolve().parent.parent / "config.example.toml"
    out.write_text(render(), encoding="utf-8")
    print(f"wrote {out}")
